- hosts: Projeto-app
  become: yes
  tasks: 
    - name: Git Clone do app
      git:
        repo: https://github.com/kauanvarella/app.git
        dest: /home/ubuntu/app-homolog
        clone: yes
        version: master
        update: yes      

    - name: Web Server Homologacao
      docker_container:
        name: app-homolog
        image: webdevops/php-apache:alpine-php7
        state: started
        ports:
          - 8081:8081
        volumes:
          - /home/ubuntu/app/www:/app-homolog

    - name: Database Homologacao
      docker_container:
        name: db-homolog
        image: mysql:5
        volumes:
          - /home/ubuntu/mysqldb:/var/lib/mysql
        restart: true
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3316:3306