- hosts: Projeto-app
  become: yes
  tasks: 
    - name: Git Clone do app
      git:
        repo: https://github.com/kauanvarella/app.git
        dest: /home/ubuntu/app
        clone: yes
        version: master
        update: yes      

    - name: Criando uma rede do Docker
      docker_network:
        name: app-network

    - name: Web Server
      docker_container:
        name: app
        image: webdevops/php-apache:alpine-php7
        state: started
        ports:
          - 80:80
        volumes:
          - /home/ubuntu/app/www:/app

    - name: Database
      docker_container:
        name: db
        image: mysql:5
        # command: --default-authentication-plugin=mysql_native_password
        volumes:
          - /home/ubuntu/mysqldb:/var/lib/mysql
        restart: true
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    - name: Add a container to a network, leaving existing containers connected
      docker_network:
        name: app-network
        connected:
          - app
          - db
          - adminer
        appends: yes