- hosts: Projeto-app
  become: yes
  tasks: 
    - name: InfluxDB
      docker_container:
        name: influxdb
        image: influxdb
        state: started
        ports:
          - "8083:8083"
          - "8086:8086"
          - "25826:25826"
        volumes:
          - /home/ubuntu/influxdb:/var/lib/influxdb

    - name: Instalando Telegraf
      shell: wget -qO- https://repos.influxdata.com/influxdb.key | sudo tee /etc/apt/trusted.gpg.d/influxdb.asc >/dev/null
      shell: source /etc/os-release
      shell: echo "deb https://repos.influxdata.com/${ID} ${VERSION_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
      shell: sudo apt-get update && sudo apt-get install telegraf
      
    - name: Git Clone do app
      git:
        repo: https://github.com/kauanvarella/app.git
        dest: /home/ubuntu/app
        clone: yes
        version: master
        update: yes      

    - name: Web Server
      docker_container:
        name: app
        image: webdevops/php-apache:alpine-php7
        state: started
        ports:
          - "80:80"
        volumes:
          - /home/ubuntu/app/www:/app